[package]
name = "bevy-tetris"
version = "0.1.0"
authors = ["drecksnoob"]
edition = "2021"

[workspace]
members = [
    "tetris_plugin"
]

# Enable optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3

[features]
default = []
debug = ["tetris_plugin/debug", "bevy-inspector-egui"]

[dependencies]
bevy_egui = "0.11"
tetris_plugin = { path = "tetris_plugin" }
rand = "0.8.5"
bevy-inspector-egui = { version = "0.8", optional = true }

[dependencies.bevy]
version = "0.6"
default-features = false
features = ["render", "bevy_winit", "png"]

# Dependencies for native only.
[target.'cfg(not(target_arch = "wasm32"))'.dependencies.bevy]
version = "0.6"
default-features = false
features = ["x11"]

[dev-dependencies]
once_cell = "1.9"
